image: nixos/unstable
packages:
  - nixos.neovim
  - nixos.jq
sources:
  - https://git.sr.ht/~chinmay/cphelper.nvim
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - format: |
      cd cphelper.nvim
      nix develop --command stylua --check .
  - lint: |
      cd cphelper.nvim
      nvim_runtime="$(nvim --clean --headless -c 'echo $VIMRUNTIME' -c 'q' 2>&1)/lua/"
      jq --arg rt "$nvim_runtime" '.workspace.library = [$rt, "lua/"]' .emmyrc.json > .emmyrc.ci.json
      mv .emmyrc.ci.json .emmyrc.json
      nix develop --command emmylua_check --warnings-as-errors .
